sudo: false # Use Travis docker infrastructure
language: android

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
